# Generated by Django 4.0.5 on 2024-01-18 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapp', '0002_task_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='image',
            field=models.ImageField(default='Image/None/Noimage.jpg', upload_to='images/'),
        ),
    ]
